#!/bin/sh
# vi: set noet ft=sh :

set -f

configdir='/etc/wardrobe'
configfile="$configdir/wardrobe.conf"
presetpattern="$configdir/preset/%s.conf"
basedir='/root/wardrobe-backup'

rdiffbackup='rdiff-backup'
opts='--preserve-numerical-ids'
verb=3

stderr() {
	echo "$@" >&2
}

stderrapp() {
	stderr 'wardrobe:' "$@"
}

stderrpf() {
	pf="$1"; shift
	stderrapp "$pf:" "$@"
}

inform() {
	stderrapp "$@"
}

warn() {
	stderrpf 'warning' "$@"
}

die() {
	stderrpf 'error' "$@"
	exit 1
}

echocall() {
	inform "$@"
	$*
}

do_backup() {
	which "$rdiffbackup" >/dev/null || die 'could not find rdiff-backup:' "$rdiffbackup"
	from="$preset::/"
	to="$basedir/$preset"
	presetfile="$(printf "$presetpattern" "$preset")"
	if [ -r "$presetfile" ]; then
		eval "$(cat "$presetfile")"
	else
		warn 'not using a preset file, defaults will apply'
	fi
	inform "starting '$from' -> '$to'"
	echocall "$rdiffbackup" --backup-mode \
		$opts \
		--verbosity "$verb" --terminal-verbosity "$tverb" \
		"$from" "$to"
}

while getopts 'c:' opt; do
	case "$opt" in
	c)
		configfile="$OPTARG"
		;;
	*)
		die "unknown option: $opt"
		;;
	esac
done

shift $(($OPTIND - 1)) || die 'could not shift'

[ "$#" -lt 1 ] && die 'no command specified'
cmd="$1"
shift || die 'could not shift again'

if [ -e "$configfile" ]; then
	eval "$(cat "$configfile")"
else
	warn 'not using a config file, defaults will apply'
fi

# $tverb is initialized with $verb, which probably was set in the config.
: "${tverb:=$verb}"

case "$cmd" in
backup)
	[ "$#" -lt 1 ] && die 'no preset specified'
	[ "$#" -gt 1 ] && warn 'excess arguments discarded'
	preset="$1"
	do_backup
	;;
*)
	die "unknown command: $cmd"
	;;
esac
